# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Julian/Desktop/SmartCam/ov7670/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/Julian/Desktop/SmartCam/ov7670/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  C:/Users/Julian/Desktop/SmartCam/ov7670/project_1/project_1.srcs/sources_1/new/reg.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/project_1/project_1.srcs/sources_1/new/Add2.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/project_1/project_1.srcs/sources_1/new/Add3.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/framebuffer.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/project_1/project_1.srcs/sources_1/new/port_array.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/project_1/project_1.srcs/sources_1/new/shiftregister.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/project_1/project_1.srcs/sources_1/new/rgbconverter.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/linebuffer.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/project_1/project_1.srcs/sources_1/new/sobel_filter.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/ov7670_registers.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/i2c_sender.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/project_1/project_1.srcs/sources_1/new/fullbuffer.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/project_1/project_1.runs/impl_2/sync.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/dual_framebuffer.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/vga.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/ov7670_controller.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/ov7670_capture.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/debounce.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/clocking.vhd
  C:/Users/Julian/Desktop/SmartCam/ov7670/ov7670_top.vhd
}
read_xdc C:/Users/Julian/Desktop/SmartCam/ov7670/ov7670.xdc
set_property used_in_implementation false [get_files C:/Users/Julian/Desktop/SmartCam/ov7670/ov7670.xdc]

synth_design -top ov7670_top -part xc7z020clg484-1
write_checkpoint -noxdef ov7670_top.dcp
catch { report_utilization -file ov7670_top_utilization_synth.rpt -pb ov7670_top_utilization_synth.pb }
