# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib {
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/new/Add3.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/new/Add2.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/new/reg.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/framebuffer.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/new/sobel_filter.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/new/shiftreg3.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/new/rgbconverter.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/linebuffer.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/ov7670_registers.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/i2c_sender.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/new/fullbuffer.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/project_1/project_1.runs/impl_2/sync.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/dual_framebuffer.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/vga.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/ov7670_controller.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/ov7670_capture.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/debounce.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/clocking.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/ov7670_top.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/new/shiftregister.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/tb_i2c_sender.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/tb_ov7670_top.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/tb_linebuffer.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/new/tb_sync.vhd
  /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/sources_1/imports/ov7670/gauss3.vhd
  /home/ce5/Xilinx/Projects/ov7670/gauss3sum.vhd
  /home/ce5/Xilinx/Projects/ov7670/norm8.vhd
  /home/ce5/Xilinx/Projects/ov7670/sobel_x.vhd
  /home/ce5/Xilinx/Projects/ov7670/sobel_y.vhd
  /home/ce5/Xilinx/Projects/ov7670/sobel.vhd
  /home/ce5/Xilinx/Projects/ov7670/gaussfilter.vhd
  /home/ce5/Xilinx/Projects/ov7670/canny.vhd
  /home/ce5/Xilinx/Projects/ov7670/rgbconv4bit.vhd
}
read_xdc /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/constrs_1/imports/ov7670/ov7670.xdc
set_property used_in_implementation false [get_files /home/ce5/Xilinx/Projects/ov7670/project_1/project_1.srcs/constrs_1/imports/ov7670/ov7670.xdc]

synth_design -top ov7670_top -part xc7z020clg484-1
write_checkpoint -noxdef ov7670_top.dcp
catch { report_utilization -file ov7670_top_utilization_synth.rpt -pb ov7670_top_utilization_synth.pb }
